# Generated by Django 2.2.24 on 2021-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('fat_count', models.IntegerField(default=0)),
                ('stupid_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
            ],
        ),
    ]
